apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mafiascum-dev
  namespace: ccatlett2000
  labels:
    service: mafiascum-dev
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: "/"
spec:
  tls:
    - hosts:
        - forum.staging.mafiascum.net
      secretName: forum-staging-tls
  rules:
    - host: forum.staging.mafiascum.net
      http:
        paths:
          - path: /
            backend:
              serviceName: forum
              servicePort: 80
          - path: /websocket/chat/
            backend:
              serviceName: site-chat-server
              servicePort: 80
